config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'characters#index'
  resources :characters, onry: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :statuses, onry: [:index, :new, :create]
  get 'diceroll/index',to: 'diceroll#index'
  get 'diceroll/show',to: 'diceroll#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_one :status
  has_many :character_users, dependent: :destroy
  has_many :users, through: :character_users
  accepts_nested_attributes_for :status, allow_destroy: true
end

app/models/character_user.rb
class CharacterUser < ApplicationRecord
  belongs_to :user
  belongs_to :character
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/equip.rb
class Equip < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/magic.rb
class Magic < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :character, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :character_users
  has_many :characters, through: :character_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :name])
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    # binding.pry
    @characters = Character.where(params[:id]).order("created_at DESC")
    
  end

  def show
    @characters = Character.find(params[:id])
  end

  def new
    @characters = Character.new
    # @characters.character_users.build
    # @character.users << current_user
    @characters.build_status
  end

  def create
    @characters = Character.new(character_params)
    # binding.pry
    if @characters.save
      # respond_to do |format|
      #   format.html { redirect_to characters_path  }
      #   format.json 
      # end
      redirect_to characters_path
    else
      render :new
    end
  end

  def edit
    @characters = Character.find(params[:id])
  end

  def update
    @characters = Character.find(params[:id])
    if @characters.update(update_character_params)
      redirect_to characters_path
    else
      render :edit
    end
  end

  def destroy
    @characters = Character.find(params[:id])
    if @characters.destroy 
      redirect_to root_path
    end
  end


  private
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def character_params
    params.require(:character).permit(:name, :gold, {user_ids:[]},
      status_attributes: [:id, :life]
    )
  end

  def update_character_params
    params.require(:character).permit(:name, :gold, :id, {user_ids:[]},
      status_attributes: [:id, :_destroy, :life]
    )
  end
end

app/controllers/diceroll_controller.rb
class DicerollController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    @user_num = num=rand(6)+1
    @enemy_num = num=rand(6)+1
  end

  def show
    @user_num = num=rand(6)+1
    @enemy_num = num=rand(6)+1
  end

  private
  # def tweet_params
  #   params.permit(:image, :text)
  # end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
  end

  def show
  end

  def new
    @statuses = Status.new
  end

  def create
    @statuses = Status.new(status_params)
    if @statuses.save
      redirect_to new_status_path
    else
      render :index
    end
  end

  private
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def status_params
    params.require(:status).permit(:content, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
  end
  
  private

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/diceroll_helper.rb
module DicerollHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/edit.html.erb
<div>
  <%= form_with(model: @characters, local: true) do |f| %>
    <div>
     <input type="hidden" name="character[user_ids][]" value=<%="#{current_user.id}"%>>
      <%= f.text_field :name, placeholder: "Name" %>
      <%= f.hidden_field :id %>
    </div>
    <div>
      <%= f.text_field :gold, placeholder: "Gold" %>
      <%= f.hidden_field :id %>
    </div>
    <div>
      <%= f.fields_for :status do |s| %>
        <%= s.text_field :life %>
        <%= s.hidden_field :id %>
      <% end %>
    </div>
    <div>
      <%= f.submit "UPDATE" %>
      <%= link_to "戻る", characters_path %>
    </div>
      
  <% end %>
</div>

app/views/characters/index.html.erb
<% if user_signed_in? %>
<div>
  <% @characters.each do |character| %>
  <div>
    <%= link_to "#{character.name}", character_path(character.id) %>

  </div>
  <% end %>
</div>
  <%= link_to "キャラ作成", new_character_path %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<div>
  <%= link_to "ダイスバトル", diceroll_index_path %>
</div>
<% else %>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %>
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
<% end %>

app/views/characters/new.html.erb
<div>
  <%= form_with(model: @characters, local: true) do |f| %>
    <div>
     <input type="hidden" name="character[user_ids][]" value=<%="#{current_user.id}"%>>
      <%= f.label :name, "Name"%>
      <%= f.text_field :name, placeholder: "Name" %>
      <%= f.hidden_field :id %>
    </div>
    <div>
      <%= f.label :gold, "Gold"%>
      <%= f.text_field :gold, placeholder: "Gold" %>
      <%= f.hidden_field :id %>
    </div>
    <div>
      <%= f.fields_for :status do |s| %>
        <%= s.label :life, "Life" %>
        <%= s.text_field :life, placeholder: "Life" %>
        <%= s.hidden_field :id %>
      <% end %>
    </div>
    <div>
      <%= f.submit "SEND" %>
      <%= link_to "戻る", characters_path %>
    </div>
      
  <% end %>
</div>

app/views/characters/show.html.erb
<%# <div class="monster">
  <h2  id="monster">ゴブリンが現われた</h2>
</div>
<div class="start">
<%= image_tag 'gettyimages-165590923-612x612.jpg', class: 'hoge' %>
  <%# <%= link_to "戦闘開始","/diceroll/show", id: "start"%> 
<%# <%= image_tag 'gettyimages-165590923-612x612.jpg', class: 'hoge' %> 
<%# </div> %> 
<div>
  
  <div>
    <%= link_to "#{@characters.name}", edit_character_path(@characters.id) %>
    <%= link_to '削除',  character_path(@characters.id), method: :delete%>
  </div>
    
</div>

app/views/diceroll/index.html.erb
<% if user_signed_in? %>
<div class="monster">
  <h2  id="monster">ゴブリンが現われた</h2>
</div>
<div class="start">
<%= image_tag 'gettyimages-165590923-612x612.jpg', class: 'hoge' %>
  <%= link_to "戦闘開始","/diceroll/show", id: "start"%>
<%= image_tag 'gettyimages-165590923-612x612.jpg', class: 'hoge' %>
</div>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "ログイン", new_user_session_path, class: 'post' %>
<%= link_to "新規登録", new_user_registration_path, class: 'post' %>
<% end %>

app/views/diceroll/show.html.erb
<div class="battle"　type="button">
<%= link_to "戦う","/diceroll/show", id: "battle"%>
</div>
<div class="ran-away">
<%= link_to "逃げる","/" %>
</div>

<div>
<h2>あなたのダイス</h2>
</div>
<div class="saikoro" id="saikoro"><%= user = @user_num %></div>
<div>
<h2>敵のダイス</h2>
</div>
<div class="saikoro" id="saikoro"><%= enemy = @enemy_num %></div>
<% if user==enemy %> 
<p>引き分け</p>
<% elsif user>enemy %>
<p>++勝利しました++</p>
<% else user<enemy %>
<p>-負けました-</p>
<p>**GAME OVER**</p>
<% end %>

app/views/statuses/_new.html.erb
<div>
  <%= f.fields_for @statuses do |s| %>
    <%= s.text_field :life %>
  <% end %>
</div>

app/views/statuses/index.html.erb
<% if user_signed_in? %>
<%# <div class="monster">
  <h2  id="monster">ゴブリンが現われた</h2>
</div>
<div class="start">
<%= image_tag 'gettyimages-165590923-612x612.jpg', class: 'hoge' %>
  <%# <%= link_to "戦闘開始","/diceroll/show", id: "start"%> 
<%# <%= image_tag 'gettyimages-165590923-612x612.jpg', class: 'hoge' %> 
<%# </div> %> 
<%= link_to "新規登録", new_status_path %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "ログイン", new_user_session_path, class: 'post' %>
<%= link_to "新規登録", new_user_registration_path, class: 'post' %>
<% end %>